### ISSUE TITLE
[FE] 캘린더 라이브러리 리서치 및 테스트

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/airbnb-09#10]
## 기능

- [ ] 캘린더 라이브러리 리서치 & 테스트

**Comment by sungik-choi** [comment]
https://ant.design/components/date-picker/#header

**Comment by sungik-choi** [comment]
http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

**Comment by reesekimm** [comment]
- [airbnb slider component built with React](https://github.com/airbnb/rheostat)
