### ISSUE TITLE
[FE] Guest Filter 기능구현

### ISSUE THREAD

**Issue by reesekimm** [codesquad-member-2020/airbnb-09#41]
## 기능

- [x] Modal 컴포넌트 분리 및 디렉토리 구조 정리
- [x] Guest 컴포넌트 내부 상태관리 구현
    - [x] -, + 버튼 클릭시 어른/어린이/유아 인원수 변경
    - [x] -, + 버튼 클릭시 버튼 텍스트 변경
- [x] Modal toggle 기능 구현
    - [x] 메뉴 버튼 클릭시
    - [x] 저장 버튼 클릭시
    - [x] Modal 바깥 영역 클릭시
- [x] Modal Reset 기능 구현
- [x] Modal toggle 시 filter api 요청을 위한 query state 변경

**Comment by sungik-choi** [comment]
**모달 바깥 영역 클릭 시** 꺼지는 기능 구현 필요!
