### ISSUE TITLE
[TEAM] API 논의

### ISSUE THREAD

**Issue by sungik-choi** [codesquad-member-2020/airbnb-09#5]
## API 논의

- API 종류 논의
- API 별 JSON 포맷 논의

---

[HackMD](https://hackmd.io/StBBrf2USV2e0uqHHvZ0bA)

**Comment by reesekimm** [comment]
### Case 1
최초 데이터 요청시에만 서버 통신 (필터링은 client단에서 상태관리와 함께 처리)

#### 필요 API 
1. 최초 데이터 요청 (GET)

---

### Case 2
최초데이터 & 날짜, 인원, 요금에 따른 필터링시 서버 통신

#### 필요 API
1. 최초 데이터 요청 (GET)
2. 날짜 선택시 필터링된 데이터 요청 (GET)
3. 인원 선택시 필터링된 데이터 요청 (GET)
4. 요금 선택시 필터링된 데이터 요청 (GET)

**Comment by blossun** [comment]
### Case 3

숙소 예약을 위한 서버 통신

#### 필요 API

1. 숙소 예약 (POST)

   ```
   BASE_URL
   
   {
      "checkin":"2020-05-21",
      "checkout":"2020-05-23",
      "adults":1,
      "children":1,
      "infants":1,
      "roomId" : 123
   }
   ```

**Comment by blossun** [comment]
# 의논 사항

* 숙소 데이터
    * 100개 ~ 300개+
* 이미지
    * 최소 3 ~ 4개 이상
    * 이미지 정보는 한 번에 드리기
* 쿼리스트링 변수명 변경
    * price_min → priceMin, price_max → priceMax
* 전체 데이터중 제한적으로 초기 데이터를 50개 정도 넘겨주고, 필터링할 경우 필터링 조건으로 전체 데이터에서 검색해서 넘겨주기
* 로그인 기능 구현은 OAuth를 목표로 한다.
* ...

### 필요한 정보

* 검색 조건 : 날짜, 인원, 요금
* 숙소 데이터
  * 숙소 사진(대표사진, 그외 사진?), 숙소이름, 숙소게시글 제목, 간단한 설명 , 원가, 할인가, (총요금 - 서버 계산), 나라, 평점, 뱃지(슈퍼호스트)
  * 청소비, 서비스 수수료, 숙박세외 수수료 - 숙박날짜에 따라서 계산한 비용으로 넘겨주기
* 날짜를 하루만 입력받는 경우 → 무조건 최소 1박으로 날짜 정보를 넘겨받음

### 고민 사항

* 숙소 예약 시 가격 정보를 어떻게 넘길지

**Comment by blossun** [comment]
### FE랑 의논 사항

* `슈퍼호스트`를 뱃지 처럼 여러개 표시할 것인지, 그냥 `슈퍼호스트` 속성 하나로 Boolean으로 처리할지 => Boolean으로 결정

* 요금 필터링 창에서 최저가, 최고가, 평균가에 대한 정보를 별도로 서버에서 제공해줘야하는지... => 이전에 앞에서 보낸 숙소 정보를 가지고 판단함
  * 필터링이 걸려있지 않은 경우, 한정된 데이터만 넘겨줄텐데 전체 통계정보가(숙소갯수) 달라질 텐데 어떡하지 => 날짜 조건이 없는 경우 보여지지 않음
* 사진 사이즈 ? 일단 제일 큰걸 보내주는 것이 좋지 않을까 => 큰사이즈
* 기획서 뷰에 숙소명이 안보이는데 없어도 될지?
  * 숙소명? 숙소 제목, 간단한 설명을 포함하라고 하는데 길이가 어떻게 되는 건지? => 설명은 불필요. 숙소명 겸 제목만
* 어른, 아이 가격 → 구분하지 않음
* 가격은 숙박 일수로만 계산 (수용인원에 따른 가격 측정은 없음)

**Comment by blossun** [comment]
### 목 서버 
ip : 3.34.15.148

1. 전체목록
```url
http://3.34.15.148/api/mock/listing/search?checkin=2020-05-21&checkout=2020-05-23&adults=1&children=1&infants=1&priceMin=22599&priceMax=
```

2. 필터링 목록
```url
http://3.34.15.148/api/mock/listing
```
